[package]
name = "debugtui"
version = "0.7.1"
edition = "2024"
description = "Native terminal debugger using a configurable GDB/MI environment"
license = "Apache-2.0"
repository = "https://github.com/bei-li16/debugtui"

[[bin]]
name = "debugtui"
path = "src/main.rs"
test = false

[dependencies]
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
crossterm = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
unicode-width = "0.2"
svd-parser = { version = "0.14.10", features = ["expand"] }

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = true
