"""Generate independently maintained register facts, without ADS resources.

Encoding source: Cortex-R52 TRM 100026_0104_01_en, sections 4.2, 4.3 and 11.1.
The output is a description of access routes, not a claim of board support.
"""
from pathlib import Path
import argparse
import json
from tempfile import TemporaryDirectory
from register_timer_metadata import TIMER_METADATA
from register_pmu_metadata import PMU_METADATA
from register_gic_metadata import GIC_METADATA, GIC_ENCODINGS
from register_mmio_metadata import MMIO_METADATA
from register_stm_metadata import STM_METADATA
from cmsis_registers import generate_m_catalogues
from register_r52_core_metadata import r52_core_metadata, DOCUMENT as R52_DOCUMENT, VERSION as R52_VERSION

MMIO_METADATA = {**MMIO_METADATA, **STM_METADATA}

ROOT = Path(__file__).resolve().parents[1] / "profiles" / "registers"
q = json.dumps

def generate(cpu, m_profile=False, root=ROOT):
    lines = ["# Generated by scripts/generate-register-catalogues.py. No ADS runtime dependency.",
             "version = 1", f"cpu = {q(cpu)}",
             f"architecture = {q('armv7e-m' if m_profile else 'armv8-r-aarch32')}",
             'description = "Read capabilities must be verified against the selected target and backend."']
    def group(id, name, parent=None):
        lines.extend(["", "[[groups]]", f"id = {q(id)}", f"name = {q(name)}"])
        if parent: lines.append(f"parent = {q(parent)}")
    def reg(id, group, bits=32, access="rw", kind="gdb", params=None, conditions=None, fields=None, effect=False):
        gic = GIC_METADATA.get(id)
        external = MMIO_METADATA.get(id) if kind == 'mmio' else None
        core = r52_core_metadata(id) if not m_profile and kind == 'cp15' else None
        if gic:
            group = gic["group"]
        lines.extend(["", "[[registers]]", f"id = {q(id)}", f"name = {q(id.upper())}", f"group = {q(group)}", f"bits = {bits}", f"access = {q(access)}"])
        descriptions = {"cpsr":"Current status and processor mode of the selected core context.","xpsr":"Combined exception, instruction-set and application status.","sctlr":"EL1 system control, including MPU enable and execution controls.","hsctlr":"EL2 system control.","midr":"Processor implementer, part number, variant and revision.","mpuir":"Implemented EL1 MPU region capacity.","hmpuir":"Implemented EL2 MPU region capacity.","pmcr":"Performance monitor configuration and implemented event-counter count.","fpscr":"Floating-point status, exceptions and control.","prselr":"Current EL1 MPU region selector; direct region reads preserve this value.","hprselr":"Current EL2 MPU region selector; direct region reads preserve this value."}
        description = descriptions.get(id, f"{id.upper()} in the {group} register group.")
        if external:
            description = external['description']
            fields = external['fields']
            conditions = external['conditions']
            lines.append(f'scope = {q(external["scope"])}')
        if gic:
            description = gic["description"]
            fields = gic["fields"]
            conditions = gic["conditions"]
        timer = TIMER_METADATA.get(id) if group == "timer" else None
        pmu = PMU_METADATA.get(id) if group == "pmu" else None
        if pmu:
            description = pmu["description"]
            fields = pmu["fields"]
            conditions = [*(conditions or []), ("pmu.present", 1, 1)]
        if timer:
            description = timer["description"]
            fields = timer["fields"]
            conditions = [*(conditions or []), ("timer.present", 1, 1)]
        if id.startswith(('prbar','hprbar')) and id[-1:].isdigit(): description = "MPU region base address, permissions, shareability and execute-never attributes."
        if id.startswith(('prlar','hprlar')) and id[-1:].isdigit(): description = "MPU region inclusive limit, memory-attribute index and enable state."
        if core:
            description = core['description']
            fields = core['fields']
            if cpu == 'cortex-r52+':
                description += ' Inherited R52 definition only; R52+ physical identity and differences remain unverified.'
        if group in ('single', 'double', 'quad'): description = "Floating-point storage view; overlapping S/D/Q aliases share one physical pair sample. MVFR controls implemented capacity; FPEXC.EN and traps control access."
        if group == 'vfp' and id != 'fpscr': description = ("Floating-point storage view; aliases use the same source sample. Availability depends on the implemented extension." if m_profile else "Raw floating-point identification or enable-control register; observation never enables the FPU.")
        lines.append(f"description = {q(description)}")
        params = params or {"name":id}
        route = [f"kind = {q(kind)}"] + [f"{key} = {q(value)}" for key,value in params.items()]
        lines.append("reader = { " + ", ".join(route) + " }")
        if core:
            assert bits == 32 and tuple(params[key] for key in ('op1','crn','crm','op2')) == core['encoding'], f'R52 encoding mismatch: {id}'
            lines.append(f'source = {{ document = {q(R52_DOCUMENT)}, version = {q(R52_VERSION)}, number = "100026_0104_01_en", section = {q(core["section"])}, page = {core["page"]} }}')
            lines.append(f'confidence = {q(core["confidence"])}')
            if core['reset'] is not None:
                lines.append(f'reset = {core["reset"]}')
        if group == "core" and kind == "gdb" and not fields and (id in ("sp", "lr", "pc") or id.startswith("r") and id[1:].isdigit()):
            lines.append(f'writer = {{ kind = "gdb_integer", name = {q(id)} }}')
            lines.append('write = { bits = 32, access = "read_write", effect = "modify", constraint = { kind = "none" }, read_side_effect = false, fields = [], reserved = "unknown", read_only_write = "unknown", verification = { kind = "modified" } }')
        elif not m_profile and group in ("single", "double", "quad"):
            lines.append(f'writer = {{ kind = "vfp", name = {q(id)} }}')
            lines.append(f'write = {{ bits = {bits}, access = "read_write", effect = "modify", constraint = {{ kind = "none" }}, read_side_effect = false, fields = [], reserved = "unknown", read_only_write = "unknown", verification = {{ kind = "modified" }} }}')
        if effect: lines.append("read_side_effect = true")
        if external:
            lines.append(f'access_condition = {q(external["access_condition"])}')
        if kind in ("cp15", "cp15_64"):
            condition = (core or timer or pmu or gic)["access_condition"] if (core or timer or pmu or gic) else "Halted physical core; access depends on current EL, traps and debug authorization."
            lines.append(f'access_condition = {q(condition)}')
        for condition in conditions or []:
            fact, minimum = condition[:2]
            lines.extend(["[[registers.conditions]]", f"fact = {q(fact)}", f"min = {minimum}"])
            if len(condition) == 3:
                lines.append(f"max = {condition[2]}")
        for entry in fields or []:
            if isinstance(entry, dict):
                name, segments, enums = entry["name"], entry["segments"], entry["enums"]
            else:
                name, segments, enums = entry
            lines.extend(["[[registers.fields]]", f"name = {q(name)}", "segments = [" + ", ".join(f"{{ offset = {offset}, width = {width} }}" for offset,width in segments) + "]"])
            field_descriptions = {"N":"Negative condition flag.","Z":"Zero condition flag.","C":"Carry condition flag.","V":"Overflow condition flag.","Q":"Cumulative saturation flag.","IT":"If-Then execution state, assembled from its two non-contiguous bit ranges.","M":"Current AArch32 processor mode.","BASE":"Region base address bits [31:6].","LIMIT":"Inclusive region limit address bits [31:6]; low address bits are all ones.","EN":"Region enable.","XN":"Execute-never attribute.","AP":"Region data access permission.","SH":"Region shareability.","AttrIndx":"Index into memory attribute registers."}
            description = entry["description"] if isinstance(entry, dict) else field_descriptions.get(name,name+' field.')
            lines.append(f"description = {q(description)}")
            if isinstance(entry, dict) and entry["access"]:
                lines.append(f'access = {q(entry["access"])}')
            for value, enum in enums:
                lines.extend(["[[registers.fields.enums]]", f"value = {q(str(value))}", f"name = {q(enum)}"])
    for id, name in [("core","Core"),("simd","SIMD"),("system","System")]: group(id,name)
    for n in range(13): reg(f"r{n}","core")
    for name in ["sp","lr","pc"]: reg(name,"core")
    flags = [(name,[(bit,1)],[]) for name,bit in [("N",31),("Z",30),("C",29),("V",28),("Q",27)]]
    if m_profile:
        flags += [("T",[(24,1)],[]),("IPSR",[(0,9)],[])]
        reg("xpsr","core",fields=flags)
        for name in ["msp","psp","primask","basepri","faultmask","control"]: reg(name,"core")
    else:
        flags += [("IT",[(25,2),(10,6)],[]),("GE",[(16,4)],[])]
        flags += [(name,[(bit,1)],[]) for name,bit in [("E",9),("A",8),("I",7),("F",6),("T",5)]]
        flags += [("M",[(0,5)],[(16,"AArch32_USR"),(17,"AArch32_FIQ"),(18,"AArch32_IRQ"),(19,"AArch32_SVC"),(23,"AArch32_ABT"),(26,"AArch32_HYP"),(27,"AArch32_UND"),(31,"AArch32_SYS")])]
        reg("cpsr","core",fields=flags)
        for mode in ["irq","fiq","und","abt","svc","hyp"]:
            group(mode,mode.upper(),"core")
            for name in ([f"r{n}_{mode}" for n in range(8,13)] if mode == "fiq" else []) + [f"sp_{mode}","elr_hyp" if mode == "hyp" else f"lr_{mode}",f"spsr_{mode}"]:
                reg(name,mode,kind="banked",params={"name":name})
        for id in ["id","control","exceptions","mpu_el1","mpu_el2","pmu","gic","timer","virt","debug"]: group(id,id.upper(),"system")
        for id, name in [("gic_icc","Physical ICC"),("gic_ich","Hyp ICH"),("gic_icv","Virtual ICV backing aliases")]:
            group(id,name,"gic")
        group('gicd', 'Cluster Distributor MMIO', 'gic')
        group('gicr', 'Core Redistributor MMIO', 'gic')
        group('debug_external', 'Core External Debug MMIO', 'debug')
        group('stm', 'Chip STM Control', 'system')
        group('stm_core', 'STM Identity and Configuration', 'stm')
        group('stm_hwe', 'Optional STM Hardware Events', 'stm')
        group('stm_dma', 'Optional STM DMA Control', 'stm')
        for name, metadata in MMIO_METADATA.items():
            reg(name, metadata['group'], bits=metadata['bits'], access=metadata['access'], kind='mmio',
                params=dict(component=metadata['component'],offset=metadata['offset'],require_owner_mapping=True),
                effect=metadata['effect'])
        # Tuples are (Op1, CRn, CRm, Op2), independently checked against TRM read encodings.
        encodings = {
            "midr":(0,0,0,0),"ctr":(0,0,0,1),"mpidr":(0,0,0,5),"id_pfr0":(0,0,1,0),"id_pfr1":(0,0,1,1),"id_dfr0":(0,0,1,2),
            "sctlr":(0,1,0,0),"cpacr":(0,1,0,2),"vbar":(0,12,0,0),"contextidr":(0,13,0,1),"tpidrurw":(0,13,0,2),"tpidruro":(0,13,0,3),"tpidrprw":(0,13,0,4),
            "dfsr":(0,5,0,0),"ifsr":(0,5,0,1),"adfsr":(0,5,1,0),"aifsr":(0,5,1,1),"dfar":(0,6,0,0),"ifar":(0,6,0,2),
            "mpuir":(0,0,0,4),"prselr":(0,6,2,1),"mair0":(0,10,2,0),"mair1":(0,10,2,1),
            "hsctlr":(4,1,0,0),"hcr":(4,1,1,0),"hdcr":(4,1,1,1),"hcptr":(4,1,1,2),"hstr":(4,1,1,3),"hsr":(4,5,2,0),"hdfar":(4,6,0,0),"hifar":(4,6,0,2),"hvbar":(4,12,0,0),"htpidr":(4,13,0,2),
            "hmpuir":(4,0,0,4),"hprselr":(4,6,2,1),"hprenr":(4,6,1,1),"hmair0":(4,10,2,0),"hmair1":(4,10,2,1),
            "pmcr":(0,9,12,0),"pmceid0":(0,9,12,6),"pmceid1":(0,9,12,7),"pmcntenset":(0,9,12,1),"pmcntenclr":(0,9,12,2),"pmovsr":(0,9,12,3),"pmselr":(0,9,12,5),"pmxevtyper":(0,9,13,1),"pmxevcntr":(0,9,13,2),"pmuserenr":(0,9,14,0),"pmintenset":(0,9,14,1),"pmintenclr":(0,9,14,2),"pmovsset":(0,9,14,3),"pmccfiltr":(0,14,15,7),
            "icc_ctlr":(0,12,12,4),"icc_sre":(0,12,12,5),"icc_pmr":(0,4,6,0),"icc_rpr":(0,12,11,3),"icc_ap0r0":(0,12,8,4),"icc_ap1r0":(0,12,9,0),"icc_iar0":(0,12,8,0),"icc_iar1":(0,12,12,0),"ich_vtr":(4,12,11,1),
            "cntfrq":(0,14,0,0),"cntkctl":(0,14,1,0),"cntp_tval":(0,14,2,0),"cntp_ctl":(0,14,2,1),"cntv_tval":(0,14,3,0),"cntv_ctl":(0,14,3,1),"cnthctl":(4,14,1,0),"cnthp_tval":(4,14,2,0),"cnthp_ctl":(4,14,2,1),
        }
        encodings.update(GIC_ENCODINGS)
        for name,(op1,crn,crm,op2) in encodings.items():
            groupid = "gic" if name.startswith(("icc_", "ich_")) else "timer" if name.startswith("cnt") else "pmu" if name.startswith("pm") else "mpu_el2" if name in ["hmpuir","hprselr","hprenr","hmair0","hmair1"] else "mpu_el1" if name in ["mpuir","prselr","mair0","mair1"] else "virt" if name.startswith("h") else "id" if name in ["midr","ctr","mpidr"] or name.startswith("id_") else "exceptions" if name in ["dfsr","ifsr","adfsr","aifsr","dfar","ifar"] else "control"
            readonly = name.startswith("id_") or name in ["midr","ctr","mpidr","mpuir","hmpuir","pmceid0","pmceid1","icc_rpr","icc_iar0","icc_iar1","ich_vtr"]
            reg(name,groupid,access=GIC_METADATA[name]["access"] if name in GIC_METADATA else "ro" if readonly else "rw",kind="cp15",params=dict(cp=15,op1=op1,crn=crn,crm=crm,op2=op2),effect=name.startswith("icc_iar"))
        for level,count in [(1,24),(2,24)]:
            for n in range(count):
                for limit in [False,True]:
                    name = ("h" if level==2 else "") + ("prlar" if limit else "prbar") + str(n)
                    fields = [("LIMIT" if limit else "BASE",[(6,26)],[])]
                    fields += [("EN",[(0,1)],[]),("AttrIndx",[(1,3)],[])] if limit else [("XN",[(0,1)],[]),("AP",[(1,2)],[]),("SH",[(3,2)],[])]
                    reg(name,f"mpu_el{level}",kind="cp15",params=dict(cp=15,op1=(0 if level==1 else 4)+n//16,crn=6,crm=8+(n%16)//2,op2=4*(n%2)+int(limit)),conditions=[(f"mpu.el{level}.regions",n+1)],fields=fields)
        for name,op1,crm,access in [("pmccntr",0,9,"rw"),("cntpct",0,14,"ro"),("cntvct",1,14,"ro"),("cntp_cval",2,14,"rw"),("cntv_cval",3,14,"rw"),("cntvoff",4,14,"rw"),("cnthp_cval",6,14,"rw")]:
            reg(name,"pmu" if name=="pmccntr" else "timer",bits=64,access=access,kind="cp15_64",params=dict(cp=15,op1=op1,crm=crm))
        for bank in range(2):
            for n in range(4):
                reg(f"icv_ap{bank}r{n}","gic_icv",kind="alias",params=dict(source=f"ich_ap{bank}r{n}",offset=0))
        for name,op1,crn,crm,op2 in [("icc_eoir0",0,12,8,1),("icc_eoir1",0,12,12,1),("icc_dir",0,12,11,1)]:
            reg(name,"gic_icc",access="wo",kind="cp15",params=dict(cp=15,op1=op1,crn=crn,crm=crm,op2=op2))
        for name,op1 in [("icc_sgi0r",2),("icc_sgi1r",0),("icc_asgi1r",1)]:
            reg(name,"gic_icc",bits=64,access="wo",kind="cp15_64",params=dict(cp=15,op1=op1,crm=12))
        for n in range(4):
            for typename,crm in [("pmevcntr",8),("pmevtyper",12)]:
                reg(f"{typename}{n}","pmu",kind="cp15",params=dict(cp=15,op1=0,crn=14,crm=crm,op2=n),conditions=[("pmu.counters",n+1)])
    group("vfp","Floating point","simd")
    if not m_profile:
        group("quad","Quad","simd")
        group("double","Double","simd")
        group("single","Single","simd")
    for n in range(16 if m_profile else 32):
        reg(f"d{n}","vfp" if m_profile else "double",bits=64,kind="gdb" if m_profile else "vfp",conditions=[("vfp.d_registers",n+1)])
    for n in range(32):
        reg(f"s{n}","vfp" if m_profile else "single",kind="alias",params=dict(source=f"d{n//2}",offset=32*(n%2)),conditions=[("vfp.d_registers",n//2+1)])
    if not m_profile:
        for n in range(16):
            reg(f"q{n}","quad",bits=128,kind="vfp",conditions=[("vfp.neon",1)])
        for name in ["fpsid","mvfr0","mvfr1","mvfr2","fpexc"]:
            reg(name,"vfp",access="rw" if name=="fpexc" else "ro",kind="vfp")
    reg("fpscr","vfp",kind="gdb" if m_profile else "vfp",conditions=[("vfp.present",1)])
    root.mkdir(parents=True,exist_ok=True)
    (root / f"{cpu}.toml").write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Compare regenerated files without changing tracked catalogues')
    args = parser.parse_args()
    def generate_all(root):
        generate("cortex-r52", root=root)
        generate("cortex-r52+", root=root)
        with TemporaryDirectory(prefix='debugtui-legacy-m-regfile-') as legacy:
            generate("cortex-m4", True, root=Path(legacy))
            generate_m_catalogues(root, (Path(legacy) / 'cortex-m4.toml').read_text(encoding='utf-8'))
    if args.check:
        with TemporaryDirectory(prefix='debugtui-register-catalogues-') as temporary:
            candidate = Path(temporary)
            generate_all(candidate)
            for file in candidate.iterdir():
                if file.read_bytes() != (ROOT / file.name).read_bytes():
                    raise SystemExit(f"Regeneration mismatch: {file.name}")
        print('6 catalogues match offline regeneration; pinned CMSIS inputs verified; tracked files unchanged')
    else:
        generate_all(ROOT)
